/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CollegeAdmin;

import Business.College.Program;
import Business.College.ProgramDirectory;
import Business.Courses.Courses;
import Business.Organization.CollegeOrganization;
import Business.Organization.Organization;
import Business.Role.ProfessorRole;
import Business.Role.RARequest;
import Business.Role.RARole;
import Business.Role.TARequest;
import Business.Role.TARole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krunal
 */
public class ManageRARJPanel extends javax.swing.JPanel {

    private CollegeOrganization org;
    private JPanel userProcessContainer;
    private ProgramDirectory pdir;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageRARJPanel(JPanel userProcessContainer, Organization org) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.org = (CollegeOrganization) org;

        this.pdir = this.org.getPD();
        populateTable();
        populateCombo();
             
        tblTARequest.getTableHeader().setFont(new Font("Tahoma",Font.CENTER_BASELINE,18));

    }

    public void populateCombo() {
        cmbStudentsName.removeAllItems();
        for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getRole() instanceof RARole) {
                cmbStudentsName.addItem(ua);
            }
        }
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTARequest.getModel();

        model.setRowCount(0);
       
        for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
            if(ua.getRole() instanceof ProfessorRole){
                ProfessorRole role = (ProfessorRole)ua.getRole();
                for(RARequest rr : role.getRArequests()){
                    Object[] row = new Object[2];
                    row[0] = rr;
                    
                    row[1] = rr.getStatus();

                    model.addRow(row);
                }
            }
        }
        
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        cmbStudentsName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTARequest = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        backJButton.setBackground(new java.awt.Color(51, 153, 255));
        backJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage RA Requests");

        btnApprove.setBackground(new java.awt.Color(51, 153, 255));
        btnApprove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        cmbStudentsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudentsNameActionPerformed(evt);
            }
        });
        cmbStudentsName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbStudentsNamePropertyChange(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Select User Account :");

        tblTARequest.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTARequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "RA", "Status"
            }
        ));
        tblTARequest.setRowHeight(20);
        jScrollPane2.setViewportView(tblTARequest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backJButton)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbStudentsName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnApprove)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStudentsName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(backJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);

        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CollegeAdminWorkAreaJPanel panel = (CollegeAdminWorkAreaJPanel) component;
        //panel.plotgraph();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:

        int selected = tblTARequest.getSelectedRow();
        if (selected >= 0) {
            UserAccount ua = (UserAccount) cmbStudentsName.getSelectedItem();
            RARequest tar = (RARequest) tblTARequest.getValueAt(selected, 0);
            UserAccount prof = tar.getProfessor();
            ProfessorRole role = (ProfessorRole)prof.getRole();
            Boolean flag = role.AssignRA(ua);
            if (flag) {
                JOptionPane.showMessageDialog(null, "RA Account asssigned");

                role.removeRequest(tar);
                populateTable();
            } else {
                JOptionPane.showMessageDialog(null, "RA Account already assigned to the course");
            }
        }

    }//GEN-LAST:event_btnApproveActionPerformed

    private void cmbStudentsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudentsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudentsNameActionPerformed

    private void cmbStudentsNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbStudentsNamePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudentsNamePropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton btnApprove;
    private javax.swing.JComboBox cmbStudentsName;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTARequest;
    // End of variables declaration//GEN-END:variables
}
