/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.StudentRole;

import Business.College.Program;
import Business.Feeds.Feeds;
import Business.Organization.CollegeOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author krunal
 */
public class StudentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StudentWorkAreaJPanel
     */
    JPanel userProcessContainer;

    CollegeOrganization organization;
    UserAccount ua;

    Program program;

    public StudentWorkAreaJPanel(JPanel userProcessContainer, Organization organization, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = (CollegeOrganization) organization;
        this.ua = ua;
        for (Program prog : this.organization.getPD().getDirectory()) {
            for (UserAccount u : prog.getStudents()) {
                if (u.getId() == ua.getId()) {
                    this.program = prog;
                    break;
                }
            }

        }

        populateTable();

        tblFeeds.getTableHeader().setFont(new Font("Tahoma", Font.CENTER_BASELINE, 18));

    }

    public void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblFeeds.getModel();
        model.setRowCount(0);

        //for (Program pd : .getPD().getDirectory()) {
        Object[] row = new Object[2];
        for (Feeds fd : ua.getFeedsList()) {

            row[0] = fd.getMessage();
            row[1] = fd.getMessageTime();
            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeeds = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnRegisterForCourses = new javax.swing.JButton();
        btnTime = new javax.swing.JButton();
        btnSubmitAssignment = new javax.swing.JButton();
        btnCheckGrades = new javax.swing.JButton();
        btnViewAssignments = new javax.swing.JButton();
        btnActiveRegistration = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblFeeds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblFeeds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Notifications", "Time"
            }
        ));
        tblFeeds.setRowHeight(20);
        jScrollPane1.setViewportView(tblFeeds);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome Student");

        btnRegisterForCourses.setBackground(new java.awt.Color(51, 153, 255));
        btnRegisterForCourses.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegisterForCourses.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterForCourses.setText("Register for courses");
        btnRegisterForCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterForCoursesActionPerformed(evt);
            }
        });

        btnTime.setBackground(new java.awt.Color(51, 153, 255));
        btnTime.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTime.setForeground(new java.awt.Color(255, 255, 255));
        btnTime.setText("Book Time Slot");
        btnTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimeActionPerformed(evt);
            }
        });

        btnSubmitAssignment.setBackground(new java.awt.Color(51, 153, 255));
        btnSubmitAssignment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSubmitAssignment.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitAssignment.setText("Submit Assignment");
        btnSubmitAssignment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitAssignmentActionPerformed(evt);
            }
        });

        btnCheckGrades.setBackground(new java.awt.Color(51, 153, 255));
        btnCheckGrades.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCheckGrades.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckGrades.setText("Check Grades");
        btnCheckGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckGradesActionPerformed(evt);
            }
        });

        btnViewAssignments.setBackground(new java.awt.Color(51, 153, 255));
        btnViewAssignments.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnViewAssignments.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAssignments.setText("View Assignment Statements ");
        btnViewAssignments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAssignmentsActionPerformed(evt);
            }
        });

        btnActiveRegistration.setBackground(new java.awt.Color(51, 153, 255));
        btnActiveRegistration.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnActiveRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnActiveRegistration.setText("Active Registration");
        btnActiveRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActiveRegistrationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegisterForCourses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmitAssignment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckGrades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewAssignments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnActiveRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegisterForCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmitAssignment, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(btnCheckGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewAssignments, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActiveRegistration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterForCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterForCoursesActionPerformed
        // TODO add your handling code here:

        if (!(program instanceof Program)) {
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }

        StudentCourseRegistrationJPanel panel = new StudentCourseRegistrationJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("StudentCourseRegistrationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRegisterForCoursesActionPerformed

    private void btnTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimeActionPerformed
        // TODO add your handling code here:
        if (!(program instanceof Program)) {
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }

        TimeSlotJPanel panel = new TimeSlotJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("StudentCourseRegistrationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnTimeActionPerformed

    private void btnSubmitAssignmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitAssignmentActionPerformed
        // TODO add your handling code here:
        
        if(!(program instanceof Program)){
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }
        AssignmentSubmissionJPanel panel = new AssignmentSubmissionJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("AssignmentSubmissionJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSubmitAssignmentActionPerformed

    private void btnCheckGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckGradesActionPerformed
        // TODO add your handling code here:
        
        if(!(program instanceof Program)){
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }
        CheckGradesJPanel panel = new CheckGradesJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("CheckGradesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnCheckGradesActionPerformed

    private void btnViewAssignmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAssignmentsActionPerformed
        // TODO add your handling code here:
        if(!(program instanceof Program)){
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }
        ViewAssignmentJPanel panel = new ViewAssignmentJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("ViewAssignmentJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewAssignmentsActionPerformed

    private void btnActiveRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActiveRegistrationActionPerformed
        // TODO add your handling code here:
        if(!(program instanceof Program)){
            JOptionPane.showMessageDialog(null, "Please add program and courses");
            return;
        }
        ActiveRegistrationJPanel panel = new ActiveRegistrationJPanel(userProcessContainer, ua, organization, program);
        userProcessContainer.add("ActiveRegistrationJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnActiveRegistrationActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActiveRegistration;
    private javax.swing.JButton btnCheckGrades;
    private javax.swing.JButton btnRegisterForCourses;
    private javax.swing.JButton btnSubmitAssignment;
    private javax.swing.JButton btnTime;
    private javax.swing.JButton btnViewAssignments;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFeeds;
    // End of variables declaration//GEN-END:variables
}
