/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ProfessorRole;

import Business.College.Program;
import Business.Courses.Courses;
import Business.Organization.CollegeOrganization;
import Business.Role.TAHours;
import Business.Role.TARole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author karan
 */
public class ViewTimesheetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewTimesheetJPanel
     */
    JPanel userProcessContainer;
    CollegeOrganization organization;
    UserAccount userAccount;
    Program program;

    ViewTimesheetJPanel(JPanel userProcessContainer, Program program, UserAccount userAccount, CollegeOrganization organization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.program = program;
        this.userAccount = userAccount;
        this.organization = organization;
        populateTAdropdown();
        tblTimesheetDetails.setVisible(false);
        
        tblTimesheetDetails.getTableHeader().setFont(new Font("Tahoma",Font.CENTER_BASELINE,18));


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTANames = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimesheetDetails = new javax.swing.JTable();
        btnApprove = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("View Timesheets");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TA Name:");

        cmbTANames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTANamesActionPerformed(evt);
            }
        });
        cmbTANames.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbTANamesPropertyChange(evt);
            }
        });

        tblTimesheetDetails.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblTimesheetDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Name", "Date", "Start Time", "End Time", "Hours worked", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTimesheetDetails.setRowHeight(20);
        jScrollPane1.setViewportView(tblTimesheetDetails);
        if (tblTimesheetDetails.getColumnModel().getColumnCount() > 0) {
            tblTimesheetDetails.getColumnModel().getColumn(0).setResizable(false);
            tblTimesheetDetails.getColumnModel().getColumn(1).setResizable(false);
            tblTimesheetDetails.getColumnModel().getColumn(2).setResizable(false);
            tblTimesheetDetails.getColumnModel().getColumn(3).setResizable(false);
            tblTimesheetDetails.getColumnModel().getColumn(4).setResizable(false);
            tblTimesheetDetails.getColumnModel().getColumn(5).setResizable(false);
        }

        btnApprove.setBackground(new java.awt.Color(51, 153, 255));
        btnApprove.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        backbtn.setBackground(new java.awt.Color(51, 153, 255));
        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setForeground(new java.awt.Color(255, 255, 255));
        backbtn.setText("<<Back");
        backbtn.setToolTipText("");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(236, 236, 236)
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(cmbTANames, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnApprove, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 413, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTANames, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblTimesheetDetails.getModel();
        model.setRowCount(0);
        UserAccount u = (UserAccount) cmbTANames.getSelectedItem();
        TARole role = (TARole) u.getRole();
        Object[] row = new Object[6];
        for (TAHours r : role.getTahours()) {
            row[0] = role.getCourse();
            row[1] = r.getDate();
            row[2] = r.getStartTime();
            row[3] = r.getEndTime();
            row[4] = (r.getTimeDuration() / 60000);
            row[5] = r;
            model.addRow(row);
        }
    }

    private void cmbTANamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTANamesActionPerformed
        // TODO add your handling code here:

        Object obj = evt.getSource();
        if (obj == cmbTANames) {
            tblTimesheetDetails.setVisible(true);
            populateTable();
        }

    }//GEN-LAST:event_cmbTANamesActionPerformed

    private void cmbTANamesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbTANamesPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTANamesPropertyChange

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTimesheetDetails.getModel();
        int selected = tblTimesheetDetails.getSelectedRow();
        if (selected >= 0) {
            TAHours hrs = (TAHours) tblTimesheetDetails.getValueAt(selected, 5);
            if (hrs.getStatus().equals("Submitted")) {
                hrs.setStatus("Approved");

                UserAccount u = (UserAccount) cmbTANames.getSelectedItem();
                u.createFeeds("TA hours for " + tblTimesheetDetails.getValueAt(selected, 1) + " has been approved.");

                //program.getProgramCoordinator().createFeeds("Program Director " + userAccount.getEmployee().getName() + " accepted course " + c.getCourseName());
            }

        }
        populateTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCourseProfJPanel panel = (ManageCourseProfJPanel) component;
        panel.populateTable();
        panel.populateFeeds();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
        
    }//GEN-LAST:event_backbtnActionPerformed

    public void populateTAdropdown() {
        cmbTANames.removeAllItems();
        for (Program pd : organization.getPD().getDirectory()) {
            for (Courses c : pd.getCourses().getCourseList()) {
                if (c.getProfessor().getId() == userAccount.getId()) {
                    for (UserAccount ua : c.getTeachingAssistant()) {
                        cmbTANames.addItem(ua);
                    }
                }

            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btnApprove;
    private javax.swing.JComboBox cmbTANames;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTimesheetDetails;
    // End of variables declaration//GEN-END:variables
}
